### ISSUE TITLE
comments through the ios app

### ISSUE THREAD

**Issue by dirk80** [StCyr/deck-react-native#16]
Hi,

I really like the deck ios app. One function I am really missing is to create comment in the ios app like in the webversion and get notifications if I am assigned to any card.

Do you think it is possible to add this feature?

Thanks.
Dirk

**Comment by StCyr** [comment]
I've implemented reading comments in the app in version 0.10.0, about to be released.

I suppose I'll implement creating comments in version 0.11.0

tickets created on framagit => https://framagit.org/StCyr/deck-react-native/-/issues/75 and https://framagit.org/StCyr/deck-react-native/-/issues/76

closing this one
