### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by ioscanner** [StCyr/deck-react-native#17]
I notice iOS 16 the Labels (tags) are shows as duplicate I have a tag Assigned and it shows twice. 
Labels drop down to Select an item is duplicating also. So you have the list looping  4 times in order.

I have the same issue with Assignees.  It shows the person assigned twice. 
Similar to the Labels.  Assignees drop down to select a person the list is looping 4 times.  user1,user2,user3,user1,user2,user3,user1....

**Comment by StCyr** [comment]
ok, bug spotted. will be fixed in next release

**Comment by StCyr** [comment]
fixed in 4785be2cc463767f3e05c35f50c28adbec89864a
