### ISSUE TITLE
Feature? Attach a document from nextcloud to card and view attachments.

### ISSUE THREAD

**Issue by ioscanner** [StCyr/deck-react-native#18]
It would be nice if we could add an attachment into the card.  So in Nextcloud app I scan a document and save it.  It would be useful to be able to attach a file uploaded already to a card.  Giving the ability to use an iOS device to work with decks without the need for a computer. 

Also, can there be a way to view the attachments? Either by opening a webpage or sending to the Nextcloud app?

**Comment by StCyr** [comment]
I'm working on implementing these features

**Comment by StCyr** [comment]
>Also, can there be a way to view the attachments? Either by opening a webpage or sending to the Nextcloud app?

I made some tests and it's actualy quite difficult. Do you know if the Nextcloud app supports a particular URI scheme (like nextcloud:// for example).

https://forums.expo.dev/t/download-and-open-file/67149/3
https://stackoverflow.com/questions/74117011/how-to-display-a-file-using-react-native

**Comment by StCyr** [comment]
ok, it works with the package react-native-file-fiewer. I just had to rebuild my dev-client

**Comment by StCyr** [comment]
see eact-native-file-viewer.

**Comment by StCyr** [comment]
will push a new version to the store today

**Comment by ioscanner** [comment]
Thanks. Did you get it uploaded? I didn’t see it post today?

Do you have a TestFlight for beta testing?

Thanks again,
Jason
