### ISSUE TITLE
Markdown Rendering

### ISSUE THREAD

**Issue by S7venLights** [StCyr/deck-react-native#21]
Rendering the markdown is a big missing factor. 
Managing a checklist on iOS is no easy task without it.

**Comment by StCyr** [comment]
Card descriptions support markdown rendering.

Are you talking about something else? or is it because of the dark theme that you don't see it properly?

**Comment by S7venLights** [comment]
Using 
'- [ ]'
and
'- [x]'
Doesn't show a check-box as it does on the android app. 

- [ ] github uses the same check-box markdown. 

The android app also automatically adds a new check-box when you hit enter to a new line, which is a nice time save.

**Comment by StCyr** [comment]
You're right.

The md rendering library that I use doesn't seem to support that unfortunately

**Comment by S7venLights** [comment]
I see, well it will be cool if you can change it when you have time. Otherwise I'll just have to use emojis or something. ✌️

**Comment by StCyr** [comment]
This will most probably make it in next version in a few days...

**Comment by StCyr** [comment]
will be available in version 0.18.0 which I'm uploading now
