### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by BiglifeMatt** [StCyr/deck-react-native#27]
All of my users that have iPhones are having issue with this app.  It connects fine to the Nextcloud server and they can see their boards and cards.  But the second they tap to open a card, the app just closes.  Using Nextcloud 24 on an on-prem Ubuntu server.  The Android app works just fine.  So I know the issue must be with the iOS app.

**Comment by Shahin-rmz** [comment]
I second this.
it seems that the user can not open a card for whatever reason.

**Comment by StCyr** [comment]
Is it solved now?
