### ISSUE TITLE
[Feature] Notifications

### ISSUE THREAD

**Issue by Dss0** [StCyr/deck-react-native#29]
First of all thanks for creating this app, it works well.
The only thing that prevents me from using this in a production environment is the absence of notifications. Optimally the deck app should push a notification when a card is assigned to the user or a card the user is assigned to is updated. Right now i'd basically have to tell our users to check the app frequently or use the official nextcloud app to receive notifications but then tell the users to open the deck app instead (as the notification of the nextcloud app just brings you to the activity screen).
Thanks in advance!

**Comment by StCyr** [comment]
Hi,

I've looked at notifications but unfortunately, the ios notification ecosystem isn't made for such a decentralized project.

To explain it in a simple way, within the ios notification ecosystem, 1 app maps to 1 server. Nextcloud Deck can be used by any amount of servers totally unrelated to each others. So, it's basically game over for me.

Nextcloud set up a notification server that can be used by any Nextcloud server to send notifications to ios apps. But these ios apps need to be signed by them. So I think it's game over for me (I'm investigating ways to get my app signed by them but it's not my priority I must admit)
