### ISSUE TITLE
Scrolling of lists

### ISSUE THREAD

**Issue by laberkeks** [StCyr/deck-react-native#5]
Scrolling in the lists not possible

Expected:
Scrolling to right list should display the lists on right

Behaviour:
Scrolling to right results in a automatic scroll back to the left lists

![image](https://user-images.githubusercontent.com/12297861/136106522-d330fc91-8433-4f60-b3f6-fc28edbf99aa.jpeg)

**Comment by StCyr** [comment]
thanks for your report. It's already on the list though:  https://framagit.org/StCyr/deck-react-native/-/issues/7

**Comment by te-online** [comment]
@StCyr Isn't it this issue that you refer to? https://framagit.org/StCyr/deck-react-native/-/issues/29 😊
