### ISSUE TITLE
Cremte Button in new card not reachable

### ISSUE THREAD

**Issue by laberkeks** [StCyr/deck-react-native#6]
Expected:
Tapping in any area outside of a Textfeld should hide the tatstatur

Current Behaviour:
- Not possible to scroll down to reach the cremte button
- Tastatur is over the Button and cant be hidded

![image](https://user-images.githubusercontent.com/12297861/136108685-840baa89-ec62-42d6-be27-b6f28fea0064.jpeg)

Workaround:
Tap title, then enter

**Comment by StCyr** [comment]
This will be fixed in next release, via commit 5c91743b4cc21f20455d19f68d1bec1904026a3d
